# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/qbsking/csce689/CBSH2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/qbsking/csce689/CBSH2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qbsking/csce689/CBSH2/CMakeFiles /home/qbsking/csce689/CBSH2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qbsking/csce689/CBSH2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CBSH2

# Build rule for target.
CBSH2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CBSH2
.PHONY : CBSH2

# fast build rule for target.
CBSH2/fast:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/build
.PHONY : CBSH2/fast

src/HLHeuristic.o: src/HLHeuristic.cpp.o

.PHONY : src/HLHeuristic.o

# target to build an object file
src/HLHeuristic.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/HLHeuristic.cpp.o
.PHONY : src/HLHeuristic.cpp.o

src/HLHeuristic.i: src/HLHeuristic.cpp.i

.PHONY : src/HLHeuristic.i

# target to preprocess a source file
src/HLHeuristic.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/HLHeuristic.cpp.i
.PHONY : src/HLHeuristic.cpp.i

src/HLHeuristic.s: src/HLHeuristic.cpp.s

.PHONY : src/HLHeuristic.s

# target to generate assembly for a file
src/HLHeuristic.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/HLHeuristic.cpp.s
.PHONY : src/HLHeuristic.cpp.s

src/ICBSNode.o: src/ICBSNode.cpp.o

.PHONY : src/ICBSNode.o

# target to build an object file
src/ICBSNode.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/ICBSNode.cpp.o
.PHONY : src/ICBSNode.cpp.o

src/ICBSNode.i: src/ICBSNode.cpp.i

.PHONY : src/ICBSNode.i

# target to preprocess a source file
src/ICBSNode.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/ICBSNode.cpp.i
.PHONY : src/ICBSNode.cpp.i

src/ICBSNode.s: src/ICBSNode.cpp.s

.PHONY : src/ICBSNode.s

# target to generate assembly for a file
src/ICBSNode.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/ICBSNode.cpp.s
.PHONY : src/ICBSNode.cpp.s

src/ICBSSearch.o: src/ICBSSearch.cpp.o

.PHONY : src/ICBSSearch.o

# target to build an object file
src/ICBSSearch.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/ICBSSearch.cpp.o
.PHONY : src/ICBSSearch.cpp.o

src/ICBSSearch.i: src/ICBSSearch.cpp.i

.PHONY : src/ICBSSearch.i

# target to preprocess a source file
src/ICBSSearch.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/ICBSSearch.cpp.i
.PHONY : src/ICBSSearch.cpp.i

src/ICBSSearch.s: src/ICBSSearch.cpp.s

.PHONY : src/ICBSSearch.s

# target to generate assembly for a file
src/ICBSSearch.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/ICBSSearch.cpp.s
.PHONY : src/ICBSSearch.cpp.s

src/LLNode.o: src/LLNode.cpp.o

.PHONY : src/LLNode.o

# target to build an object file
src/LLNode.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/LLNode.cpp.o
.PHONY : src/LLNode.cpp.o

src/LLNode.i: src/LLNode.cpp.i

.PHONY : src/LLNode.i

# target to preprocess a source file
src/LLNode.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/LLNode.cpp.i
.PHONY : src/LLNode.cpp.i

src/LLNode.s: src/LLNode.cpp.s

.PHONY : src/LLNode.s

# target to generate assembly for a file
src/LLNode.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/LLNode.cpp.s
.PHONY : src/LLNode.cpp.s

src/MDD.o: src/MDD.cpp.o

.PHONY : src/MDD.o

# target to build an object file
src/MDD.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/MDD.cpp.o
.PHONY : src/MDD.cpp.o

src/MDD.i: src/MDD.cpp.i

.PHONY : src/MDD.i

# target to preprocess a source file
src/MDD.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/MDD.cpp.i
.PHONY : src/MDD.cpp.i

src/MDD.s: src/MDD.cpp.s

.PHONY : src/MDD.s

# target to generate assembly for a file
src/MDD.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/MDD.cpp.s
.PHONY : src/MDD.cpp.s

src/RectangleReasoning.o: src/RectangleReasoning.cpp.o

.PHONY : src/RectangleReasoning.o

# target to build an object file
src/RectangleReasoning.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/RectangleReasoning.cpp.o
.PHONY : src/RectangleReasoning.cpp.o

src/RectangleReasoning.i: src/RectangleReasoning.cpp.i

.PHONY : src/RectangleReasoning.i

# target to preprocess a source file
src/RectangleReasoning.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/RectangleReasoning.cpp.i
.PHONY : src/RectangleReasoning.cpp.i

src/RectangleReasoning.s: src/RectangleReasoning.cpp.s

.PHONY : src/RectangleReasoning.s

# target to generate assembly for a file
src/RectangleReasoning.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/RectangleReasoning.cpp.s
.PHONY : src/RectangleReasoning.cpp.s

src/SingleAgentICBS.o: src/SingleAgentICBS.cpp.o

.PHONY : src/SingleAgentICBS.o

# target to build an object file
src/SingleAgentICBS.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/SingleAgentICBS.cpp.o
.PHONY : src/SingleAgentICBS.cpp.o

src/SingleAgentICBS.i: src/SingleAgentICBS.cpp.i

.PHONY : src/SingleAgentICBS.i

# target to preprocess a source file
src/SingleAgentICBS.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/SingleAgentICBS.cpp.i
.PHONY : src/SingleAgentICBS.cpp.i

src/SingleAgentICBS.s: src/SingleAgentICBS.cpp.s

.PHONY : src/SingleAgentICBS.s

# target to generate assembly for a file
src/SingleAgentICBS.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/SingleAgentICBS.cpp.s
.PHONY : src/SingleAgentICBS.cpp.s

src/agents_loader.o: src/agents_loader.cpp.o

.PHONY : src/agents_loader.o

# target to build an object file
src/agents_loader.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/agents_loader.cpp.o
.PHONY : src/agents_loader.cpp.o

src/agents_loader.i: src/agents_loader.cpp.i

.PHONY : src/agents_loader.i

# target to preprocess a source file
src/agents_loader.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/agents_loader.cpp.i
.PHONY : src/agents_loader.cpp.i

src/agents_loader.s: src/agents_loader.cpp.s

.PHONY : src/agents_loader.s

# target to generate assembly for a file
src/agents_loader.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/agents_loader.cpp.s
.PHONY : src/agents_loader.cpp.s

src/common.o: src/common.cpp.o

.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/compute_heuristic.o: src/compute_heuristic.cpp.o

.PHONY : src/compute_heuristic.o

# target to build an object file
src/compute_heuristic.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/compute_heuristic.cpp.o
.PHONY : src/compute_heuristic.cpp.o

src/compute_heuristic.i: src/compute_heuristic.cpp.i

.PHONY : src/compute_heuristic.i

# target to preprocess a source file
src/compute_heuristic.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/compute_heuristic.cpp.i
.PHONY : src/compute_heuristic.cpp.i

src/compute_heuristic.s: src/compute_heuristic.cpp.s

.PHONY : src/compute_heuristic.s

# target to generate assembly for a file
src/compute_heuristic.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/compute_heuristic.cpp.s
.PHONY : src/compute_heuristic.cpp.s

src/driver.o: src/driver.cpp.o

.PHONY : src/driver.o

# target to build an object file
src/driver.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/driver.cpp.o
.PHONY : src/driver.cpp.o

src/driver.i: src/driver.cpp.i

.PHONY : src/driver.i

# target to preprocess a source file
src/driver.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/driver.cpp.i
.PHONY : src/driver.cpp.i

src/driver.s: src/driver.cpp.s

.PHONY : src/driver.s

# target to generate assembly for a file
src/driver.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/driver.cpp.s
.PHONY : src/driver.cpp.s

src/map_loader.o: src/map_loader.cpp.o

.PHONY : src/map_loader.o

# target to build an object file
src/map_loader.cpp.o:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/map_loader.cpp.o
.PHONY : src/map_loader.cpp.o

src/map_loader.i: src/map_loader.cpp.i

.PHONY : src/map_loader.i

# target to preprocess a source file
src/map_loader.cpp.i:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/map_loader.cpp.i
.PHONY : src/map_loader.cpp.i

src/map_loader.s: src/map_loader.cpp.s

.PHONY : src/map_loader.s

# target to generate assembly for a file
src/map_loader.cpp.s:
	$(MAKE) -f CMakeFiles/CBSH2.dir/build.make CMakeFiles/CBSH2.dir/src/map_loader.cpp.s
.PHONY : src/map_loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CBSH2"
	@echo "... src/HLHeuristic.o"
	@echo "... src/HLHeuristic.i"
	@echo "... src/HLHeuristic.s"
	@echo "... src/ICBSNode.o"
	@echo "... src/ICBSNode.i"
	@echo "... src/ICBSNode.s"
	@echo "... src/ICBSSearch.o"
	@echo "... src/ICBSSearch.i"
	@echo "... src/ICBSSearch.s"
	@echo "... src/LLNode.o"
	@echo "... src/LLNode.i"
	@echo "... src/LLNode.s"
	@echo "... src/MDD.o"
	@echo "... src/MDD.i"
	@echo "... src/MDD.s"
	@echo "... src/RectangleReasoning.o"
	@echo "... src/RectangleReasoning.i"
	@echo "... src/RectangleReasoning.s"
	@echo "... src/SingleAgentICBS.o"
	@echo "... src/SingleAgentICBS.i"
	@echo "... src/SingleAgentICBS.s"
	@echo "... src/agents_loader.o"
	@echo "... src/agents_loader.i"
	@echo "... src/agents_loader.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/compute_heuristic.o"
	@echo "... src/compute_heuristic.i"
	@echo "... src/compute_heuristic.s"
	@echo "... src/driver.o"
	@echo "... src/driver.i"
	@echo "... src/driver.s"
	@echo "... src/map_loader.o"
	@echo "... src/map_loader.i"
	@echo "... src/map_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

